### ISSUE TITLE
URI string format refered to in README is not allowed

### ISSUE THREAD

**Issue by GradedJestRisk** [rafamel/ensurism#3]
The spec { type: 'string', format: 'uri'} found in [doc](https://github.com/rafamel/ensurism#environment-variables) is rejected with error message `unknown format "uri" ignored in schema at path "#/properties/data"`

See matching [test](http://github.com/GradedJestRisk/js-training/blob/master/node/npm/env-variable/type-checking.js#L19-L28) for details

Node 14.15.0 / Ubuntu 20.10

**Comment by rafamel** [comment]
Thank you for spotting this, @GradedJestRisk

I've added a couple tests for it, and it's now fixed for the *0.6.0* release.
